# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43b0a93c68a108aca2a090e5094b6194ad993084d4fd8599736d836cb4332e33c066c6c9e11878f1fb05a9cf1e35e4bfa01ffa6e9f1cea92595f8167adcd2f7b

test:
  secret_key_base: 430718cf0a99d7d3cb87ea7ee042f0f9cd0307a34c669ebef97a6c6887dea0d8522a1f84300bdd3dd60166716c68a5928449625e9645d42ee4ea26447df89139

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
